{
 "title": "BarberShop API",
 "refresh": "10s",
 "panels": [
  {
   "title": "Requests per Second",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "sum(rate(http_server_request_duration_seconds_count[1m])) by (http_route)",
     "legendFormat": "{{http_route}}"
    }
   ]
  },
  {
   "title": "P95 Latency (ms)",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 0, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_request_duration_seconds_bucket[5m])) by (le, http_route)) * 1000",
     "legendFormat": "p95 {{http_route}}"
    }
   ]
  },
  {
   "title": "Error Rate 5xx (%)",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 8, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "sum(rate(http_server_request_duration_seconds_count{http_response_status_code=~\"5..\"}[5m])) / sum(rate(http_server_request_duration_seconds_count[5m])) * 100",
     "legendFormat": "Error Rate %"
    }
   ]
  },
  {
   "title": "Appointments Created",
   "type": "stat",
   "gridPos": { "x": 12, "y": 8, "w": 6, "h": 8 },
   "targets": [
    {
     "expr": "sum(barbershop_appointments_created_total)"
    }
   ]
  },
  {
   "title": "Appointments Cancelled",
   "type": "stat",
   "gridPos": { "x": 18, "y": 8, "w": 6, "h": 8 },
   "targets": [
    {
     "expr": "sum(barbershop_appointments_cancelled_total)"
    }
   ]
  },
  {
   "title": "Login Success vs Failed",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 16, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "sum(rate(barbershop_auth_login_success_total[5m]))",
     "legendFormat": "Success"
    },
    {
     "expr": "sum(rate(barbershop_auth_login_failed_total[5m]))",
     "legendFormat": "Failed"
    }
   ]
  },
  {
   "title": ".NET Heap Memory (MB)",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 16, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "dotnet_gc_heap_size_bytes / 1024 / 1024",
     "legendFormat": "Heap MB"
    }
   ]
  }
 ]
}